---
- name: Update apt cache (for Debian-based systems)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install common packages
  ansible.builtin.package:
    name:
      - vim
      - git
      - curl
      - wget
      - rsync
      - python3-pip
    state: present
