groups:
- name: application
  rules:
  - alert: HighRequestLatency
    expr: http_request_duration_seconds_sum / http_request_duration_seconds_count > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      description: "Request latency is high on {{ $labels.instance }}."
