FROM docker:dind

# Install dependencies
RUN apk add --no-cache openjdk11

# Set up user
RUN addgroup -S jenkins && adduser -S jenkins -G jenkins
RUN chown -R jenkins:jenkins /home/jenkins

USER jenkins
WORKDIR /home/jenkins
