---
jenkins_master_port: 8080
jenkins_agent_port: 50000
jenkins_admin_user: "admin"
jenkins_admin_password: "password"
jenkins_domain: "jenkins.example.com"
jenkins_force_pull_images: false
jenkins_master_memory: "2g"
jenkins_master_memory_min: "1g"
jenkins_master_cpu_limit: "1.0"
jenkins_agent_disable_https: false
jenkins_home: "/var/jenkins_home"
jenkins_user: "jenkins"
jenkins_group: "jenkins"
jenkins_uid: 1000
jenkins_gid: 1000
jenkins_network_name: "jenkins-net"
jenkins_data_volume: "jenkins-data"
shared_workspace_volume: "shared-workspace"
jenkins_agent_secret: "mysecret"
haproxy_enabled: true
haproxy_version: "2.5"
haproxy_http_port: 80
haproxy_https_port: 443
haproxy_stats_port: 8404
haproxy_health_port: 8405
haproxy_memory_limit: "256m"
haproxy_cpu_limit: "0.5"
ssl_enabled: false
ssl_cert_path: "/etc/ssl/certs"
ssl_key_path: "/etc/ssl/private"
ssl_ca_path: "/etc/ssl/certs"
system_timezone: "Etc/UTC"
jenkins_monitoring_enabled: true
jenkins_backup_enabled: true
jenkins_vip: "192.168.33.10"
