---
- name: Install HAProxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Ensure HAProxy service is started and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
