---
- name: Ensure firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open firewall ports on Jenkins Masters
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: ["8080/tcp", "50000/tcp"]
  when: "inventory_hostname in groups['jenkins_masters']"

- name: Open firewall ports on Load Balancer
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: ["http", "https"]
  when: "inventory_hostname in groups['load_balancers']"
