---
# handlers file for common
- name: restart chrony
  service:
    name: chrony
    state: restarted

- name: restart logrotate
  service:
    name: logrotate
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
