---
# tasks file for prometheus
- name: Create Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:v2.37.0
    state: started
    restart_policy: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "{{ prometheus_config_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_data_dir }}:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

- name: Create prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
  notify: restart prometheus

- name: Create alerting rules
  template:
    src: alerting-rules.yml.j2
    dest: "{{ prometheus_config_dir }}/alerting-rules.yml"
  notify: restart prometheus
