all:
  children:
    nfs_server:
      hosts:
        nfs01:
          ansible_host: 192.168.1.10
    jenkins_masters:
      hosts:
        jenkins-master-01:
          ansible_host: 192.168.1.20
        jenkins-master-02:
          ansible_host: 192.168.1.21
    jenkins_agents:
      hosts:
        jenkins-agent-01:
          ansible_host: 192.168.1.30
    load_balancers:
      hosts:
        haproxy01:
          ansible_host: 192.168.1.40
    monitoring:
      hosts:
        monitor01:
          ansible_host: 192.168.1.50
    build_host:
      hosts:
        jenkins-agent-01:
